# Launch fcitx5 with environment variables
exec_always --no-startup-id bash -c 'export QT_QPA_PLATFORM=wayland GTK_IM_MODULE=fcitx QT_IM_MODULE=fcitx XMODIFIERS=@im=fcitx SDL_IM_MODULE=fcitx && fcitx5 -d'
