# Idle configuration
exec swayidle -w \
    timeout 300 'swaylock -f -c 000000' \
    timeout 600 'systemctl suspend' \
    after-resume '$HOME/.config/sway/scripts/reset-external-outputs.sh' \
    before-sleep 'swaylock -f -c 000000'
