# Auto lid handler
# systemd-inhibit prevents logind from handling lid events independently
exec_always systemd-inhibit --what=handle-lid-switch --who="lid-handler" --why="Custom lid handling" ~/.config/sway/scripts/lid-handler.sh
